### ISSUE TITLE
wav support missing?

### ISSUE THREAD

**Issue by dafeu** [jack-cli-cd-ripper/jack#39]
If I do a "jack -Q -g *wav" with the python3 version I get:
 *error* unsupported format SndHeaders(filetype='wav', framerate=44100, 
         nchannels=2, nframes=14427756, sampwidth=16)....
it worked with the python2 version, is there an easy fix?

**Comment by madmartin** [comment]
Hi,

what about option `--only-dae` ?

`jack --longhelp` says `--only-dae, -O                          only produce WAVs, implies --keep_wavs [no] `

**Comment by dafeu** [comment]
I don't want to create wavs, I already did that. I want jack to create a toc from the wavs and query the cd meta data. I tried it with mp3s and that still works, but not with wavs.

**Comment by pimzand** [comment]
Quick workaround would be to convert to flac (flac *.wav), and then run your query on the flac files.
This is what I used to do in the python2 version too, because of issues with the python libraries that handle wav.
You can convert the flac files back to wav, if you intend to create mp3 files. Jack will recognize the wav files its own.

I am planning to create a way to convert directly from flac to mp3 or aac.

**Comment by zzarne** [comment]
fixed in https://github.com/jack-cli-cd-ripper/jack/commit/5ba2b99d50c2a32749d3cc0181a054cfae415277.
