### ISSUE TITLE
Getting 'Please install the eyeD3 module available from http://eyed3.nicfit.net/' when eyeD3 already installed.

### ISSUE THREAD

**Issue by noodlesontoast** [jack-cli-cd-ripper/jack#41]
Getting the error as above when trying to run, even though eyeD3 is in fact installed and can be run.

eyeD3 installed via 'pip install eyed3' command.

Probably have missed something obvious, any help appreciated.

Thanks

- Same issue on linux or macOS.

**Comment by RanTalbott** [comment]
Same problem on Ubuntu 20.04.
If you look at http://eyed3.nicfit.net/ it says "Python >= 3.6 is required.", which probably means we need an older version.

But there's no clue as to which older version, or how to get it.

**Comment by pimzand** [comment]
You  have jack running using Python 2 and eyeD3 using Python 3.
I'm using Fedora, which at some point offered eyeD3 libraries both for Python 2 and Python 3,
which could be installed in parallel. If your distro offers this, then this could be used.
Currently Fedora has abandoned Python 2 altogether, which is why there now is an experimental
Python 3 port of Jack in a separate branch. You may want to check that out.
This branch uses mutagen, instead of eyeD3.

**Comment by pimzand** [comment]
closing, as this issue is fixed in branch python3-mb
