### ISSUE TITLE
python3-mb: musicbrainz_template() breaks smart metadata selection

### ISSUE THREAD

**Issue by pimzand** [jack-cli-cd-ripper/jack#44]
Before commit 4f709dbfb45549b07afd5f636885a9d24946cc97, jack would use the most recently modified cached metadata (ie, jack.freedb or jack.musicbrainz), regardless of the default metadata provider. This behaviour is now broken when musicbrainz is the default metadata provider, yet jack.freedb is the only available cached metadata. Jack now creates an empty jack.musicbrainz which will then be selected because of its newer modification date, leading to failure.

**Comment by zzarne** [comment]
should be fixed in https://github.com/jack-cli-cd-ripper/jack/commit/de42206c1076d6f0ab1fbaad7293f2f87e90033d.

I changed metadata_names() so that it

- works with any number of scrapers
- tests whether the data is usable

while still

- selecting the most recent data
- informing the user if the source is not the configured source.

Please test.

**Comment by pimzand** [comment]
Yes, works as expected. Thanks!
